In [1]:
import torch
from torch.amp import autocast
from model import MASTER
import pandas as pd

In [3]:
# 創建模型
model = MASTER(
    market_dim=21,
    feature_dim=185
)

# 放到 GPU
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

# 假資料
batch = 16
# [batch, stocks, time, features]
x = torch.randn(batch, 1822, 8, 185, device=device)
m = torch.randn(batch, 21, device=device)

# AMP版 forward
with autocast('cuda', dtype=torch.float16):
    out = model(x, m)


print(out.shape)

torch.Size([16, 1822])

In [6]:
pd.read_feather('櫃買報酬指數及成交金額.ftr')

             price       amount
Date
2015-01-05  182.84  18252821076
2015-01-06  179.74  21617016991
2015-01-07  179.70  18581502158
2015-01-08  180.34  22408731504
2015-01-09  180.66  20682092591
...            ...          ...
2025-04-10  359.32  37524464732
2025-04-11  364.56  80100106455
2025-04-14  371.10  76806780280
2025-04-15  385.09  68807135388
2025-04-16  378.69  81137676824

[2504 rows x 2 columns]

In [5]:
torch.randn(1822, 1226, 185)

tensor([[[-0.3420,  0.4465,  0.1726,  ..., -0.8360,  0.0858, -0.9700],
         [-1.1051,  1.2602,  0.5866,  ...,  0.2978,  0.6003, -1.8670],
         [ 1.6565, -0.1947, -0.0062,  ..., -0.3788, -0.2125,  0.2285],
         ...,
         [-2.4431, -1.1234,  0.0399,  ...,  1.2860,  0.2257,  1.7905],
         [ 0.0956, -1.0489, -1.1178,  ..., -0.0439,  1.9940,  1.2658],
         [-0.3987, -0.7504, -0.4054,  ..., -2.3000,  0.3035,  1.2602]],

        [[-0.9181,  0.4897,  0.3553,  ..., -0.3460, -0.0669,  0.5505],
         [ 0.4667,  0.4117,  0.2860,  ...,  0.4140,  1.4905, -0.6344],
         [-0.4393,  0.0636,  0.2727,  ...,  2.3745,  0.2393, -0.3971],
         ...,
         [ 0.2916,  0.0483,  0.1180,  ...,  2.3540, -0.5015, -0.7197],
         [ 0.6639, -1.2240, -2.0414,  ..., -1.7438, -2.6044,  0.8312],
         [-1.7139, -1.4296, -1.7307,  ...,  0.5122,  0.2719, -0.0291]],

        [[ 0.5569,  0.0363, -1.2033,  ...,  0.2270, -1.4925, -1.1957],
         [-1.5249, -0.3124,  0.9162,  ..., -1.6046, -1.2538, -0.8003],
         [ 0.9395, -1.1777,  0.0328,  ..., -2.4578, -0.8487,  0.3239],
         ...,
         [ 0.4158,  0.1775, -0.4927,  ..., -0.3120,  2.0645, -0.6350],
         [-0.2159, -0.6541, -2.6815,  ..., -0.1304, -1.7659, -0.3521],
         [-0.5428,  0.2758, -0.5767,  ...,  1.0027, -0.7544, -0.4824]],

        ...,

        [[ 0.4159, -0.8713, -0.6254,  ..., -0.6589, -1.5443, -0.6554],
         [-0.6059, -1.0043,  0.8218,  ...,  0.1843,  0.1369, -0.3479],
         [ 0.2720, -0.2850, -0.7834,  ...,  0.1746,  1.3567,  0.3852],
         ...,
         [ 1.1201, -0.0947, -0.6097,  ...,  0.5685, -1.0048,  0.0630],
         [-1.2423, -0.8755, -0.8710,  ..., -1.1973, -0.3815, -0.0041],
         [ 0.4211, -0.2904, -0.8672,  ...,  2.1601,  0.3436,  0.2618]],

        [[ 1.3827,  0.4536,  1.1859,  ..., -0.2461, -0.5765, -1.9043],
         [-0.8199, -0.5278, -0.9074,  ..., -0.8610,  1.1237, -0.4933],
         [-0.0990, -1.0105,  1.1239,  ...,  1.6039,  1.0915, -0.7817],
         ...,
         [ 1.9194,  0.4354, -0.6192,  ..., -1.2893, -1.3413, -0.4666],
         [-0.9403, -0.1267, -0.2035,  ..., -0.2107, -0.6603,  0.4452],
         [-0.9645, -0.4387,  0.5952,  ...,  1.8273,  0.5442, -0.7798]],

        [[ 0.5331,  1.9420, -0.5602,  ..., -0.3568, -0.2921,  0.6314],
         [-1.0368,  0.9431, -1.3726,  ...,  1.2869,  1.0501,  0.1097],
         [ 0.1052, -1.2759,  1.3577,  ...,  0.8566, -0.1943, -0.2425],
         ...,
         [ 0.2154, -0.4486, -0.2000,  ...,  1.0102, -0.2901,  0.5190],
         [-0.2102,  0.9154, -0.0178,  ...,  1.6865,  0.4349, -0.3867],
         [-1.6371,  1.5116, -0.9233,  ...,  0.9407,  0.1206,  0.4705]]])